# Generated by Django 6.0.4 on 2026-04-14 15:28

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'acme-corp'.", max_length=100, unique=True, verbose_name='slug')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20, verbose_name='subscription tier')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Used as the primary login credential.', max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], db_index=True, default='client', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Bypasses all permission checks.', verbose_name='superuser')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account is locked until this datetime.', null=True, verbose_name='locked until')),
                ('password_last_changed', models.DateTimeField(blank=True, null=True, verbose_name='password last changed')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='terms accepted at')),
                ('privacy_accepted_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='privacy policy version accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text="Machine-readable identifier, e.g. 'invoice:approve'.", max_length=100, unique=True, verbose_name='codename')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('resource_type', models.CharField(blank=True, help_text="The type of resource this permission applies to, e.g. 'document'.", max_length=100, verbose_name='resource type')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['resource_type', 'codename'],
                'indexes': [models.Index(fields=['resource_type'], name='idx_permission_resource_type')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='phone number')),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='alternate email')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code, e.g. 'US', 'GB'.", max_length=2, verbose_name='country')),
                ('profile_picture', models.ImageField(blank=True, help_text='Storage backend (S3/GCS) should be configured via DEFAULT_FILE_STORAGE.', null=True, upload_to='profile_pictures/%Y/%m/', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='preferences')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for a permanent assignment.', null=True, verbose_name='expires at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user role assignment',
                'verbose_name_plural': 'user role assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserRoleAssignment', through_fields=('user', 'role'), to='accounts.role', verbose_name='roles'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token hash (SHA-256)')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email verification token',
                'verbose_name_plural': 'email verification tokens',
                'abstract': False,
                'indexes': [models.Index(fields=['token_hash'], name='idx_emailver_token_hash'), models.Index(fields=['expires_at'], name='idx_emailver_expires_at'), models.Index(fields=['user', 'expires_at'], name='idx_emailver_user_expires')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('used', False), ('expires_at__gt', datetime.datetime(2026, 4, 14, 15, 28, 54, 944695, tzinfo=datetime.timezone.utc))), fields=('user',), name='uq_emailver_one_active_per_user')],
            },
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token hash (SHA-256)')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_link_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'magic link token',
                'verbose_name_plural': 'magic link tokens',
                'abstract': False,
                'indexes': [models.Index(fields=['token_hash'], name='idx_magiclink_token_hash'), models.Index(fields=['expires_at'], name='idx_magiclink_expires_at'), models.Index(fields=['user', 'expires_at'], name='idx_magiclink_user_expires')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token hash (SHA-256)')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
                'abstract': False,
                'indexes': [models.Index(fields=['token_hash'], name='idx_pwreset_token_hash'), models.Index(fields=['expires_at'], name='idx_pwreset_expires_at'), models.Index(fields=['user', 'expires_at'], name='idx_pwreset_user_expires')],
            },
        ),
        migrations.CreateModel(
            name='UserMFA',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('totp', 'TOTP (Authenticator App)'), ('webauthn', 'WebAuthn (Hardware Key / Passkey)')], db_index=True, max_length=20, verbose_name='method')),
                ('secret_encrypted', models.TextField(help_text='AES-256 encrypted TOTP secret or WebAuthn credential ID.', verbose_name='encrypted secret')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('backup_codes_hash', models.TextField(blank=True, help_text='Newline-separated bcrypt hashes of one-time backup codes.', null=True, verbose_name='backup codes hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user MFA',
                'verbose_name_plural': 'user MFA records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_mfa_user_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uq_mfa_one_active_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, help_text="The 'jti' claim from the SimpleJWT refresh token.", max_length=255, unique=True, verbose_name='JWT ID (jti)')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('revoked', models.BooleanField(db_index=True, default=False, verbose_name='revoked')),
                ('device_name', models.CharField(blank=True, help_text="Human-readable label, e.g. 'Chrome 124 on Windows 11'.", max_length=255, verbose_name='device name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user refresh token',
                'verbose_name_plural': 'user refresh tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked', 'expires_at'], name='idx_refreshtoken_user_revoked_exp'), models.Index(fields=['jti'], name='idx_refreshtoken_jti'), models.Index(fields=['expires_at'], name='idx_refreshtoken_expires')],
            },
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'expires_at'], name='idx_roleassign_user_expires'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_user_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['email'], name='idx_user_email_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='idx_user_tenant_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['locked_until'], name='idx_user_locked_until'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='uq_user_email_not_deleted'),
        ),
    ]
