# Generated by Django 6.0.4 on 2026-04-14 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailverificationtoken',
            name='uq_emailver_one_active_per_user',
        ),
        migrations.RenameIndex(
            model_name='userrefreshtoken',
            new_name='idx_rftoken_user_rev_exp',
            old_name='idx_refreshtoken_user_revoked_exp',
        ),
        migrations.AddConstraint(
            model_name='emailverificationtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('used', False), ('expires_at__gt', datetime.datetime(2026, 4, 14, 15, 31, 4, 768698, tzinfo=datetime.timezone.utc))), fields=('user',), name='uq_emailver_one_active_per_user'),
        ),
    ]
