# Generated by Django 5.2.4 on 2026-04-15 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_emailverificationtoken_uq_emailver_one_active_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailverificationtoken',
            name='uq_emailver_one_active_per_user',
        ),
        migrations.AddConstraint(
            model_name='emailverificationtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('used', False), ('expires_at__gt', datetime.datetime(2026, 4, 15, 9, 49, 34, 540898, tzinfo=datetime.timezone.utc))), fields=('user',), name='uq_emailver_one_active_per_user'),
        ),
    ]
