# Generated by Django 5.2.4 on 2026-05-26 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emailverificationtoken_uq_emailver_one_active_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailverificationtoken',
            name='uq_emailver_one_active_per_user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_picture_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Google profile picture URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, help_text="Immutable Google account 'sub' claim. Set on first Google sign-in; used to locate the user on subsequent logins.", max_length=255, null=True, unique=True, verbose_name='Google subject ID'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256 token hash'),
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256 token hash'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256 token hash'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(help_text="Machine-readable key, e.g. 'project:delete'.", max_length=100, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource_type',
            field=models.CharField(blank=True, help_text="Resource this permission applies to, e.g. 'document'.", max_length=100, verbose_name='resource type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Primary login credential — normalised to lowercase.', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Grants Django admin site access.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this datetime (UTC).', null=True, verbose_name='locked until'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('client', 'Client')], db_index=True, default='client', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code, e.g. 'US', 'GB'.", max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Configure DEFAULT_FILE_STORAGE to use S3/GCS in production.', null=True, upload_to='profile_pictures/%Y/%m/', verbose_name='profile picture'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='idx_user_role_active'),
        ),
        migrations.AddConstraint(
            model_name='emailverificationtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('used', False), ('expires_at__gt', datetime.datetime(2026, 5, 26, 6, 52, 1, 6231, tzinfo=datetime.timezone.utc))), fields=('user',), name='uq_emailver_one_active_per_user'),
        ),
    ]
