# Generated by Django 5.2.4 on 2026-06-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_emailverificationtoken_uq_emailver_one_active_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailverificationtoken',
            name='uq_emailver_one_active_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='uq_user_email_not_deleted',
        ),
    ]
